# Generated by Django 6.0.3 on 2026-03-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("dark", "🌑 다크 (GitHub Dark)"),
                            ("light", "☀️ 라이트 모던"),
                            ("magazine", "📰 매거진 (신문 스타일)"),
                            ("minimal", "⬜ 미니멀 화이트"),
                        ],
                        default="dark",
                        max_length=20,
                        verbose_name="블로그 테마",
                    ),
                ),
                (
                    "blog_title",
                    models.CharField(
                        default="My Blog", max_length=100, verbose_name="블로그 제목"
                    ),
                ),
                (
                    "blog_description",
                    models.CharField(
                        default="생각을 기록하는 공간", max_length=200, verbose_name="블로그 설명"
                    ),
                ),
            ],
            options={
                "verbose_name": "사이트 설정",
                "verbose_name_plural": "사이트 설정",
            },
        ),
    ]
